# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThermoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('local', models.CharField(max_length=150, verbose_name='Local')),
                ('device_ip', models.CharField(max_length=15, verbose_name='Ip do dispositivo')),
                ('capture_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Captura')),
            ],
            options={
                'verbose_name': 'Thermo Info',
                'verbose_name_plural': "Thermo Info's",
            },
        ),
    ]
