# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedaddress',
            name='max_temperature',
            field=models.FloatField(default=20.0, verbose_name='Maximum temperature permitted'),
        ),
    ]
