# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0003_allowedaddress_days_to_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermoinfo',
            name='local',
        ),
        migrations.AddField(
            model_name='allowedaddress',
            name='local',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Local'),
        ),
    ]
