# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0004_auto_20160727_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermoinfo',
            name='device_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermo_info', to='catcher.AllowedAddress', verbose_name='Device'),
        ),
    ]
