# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0005_auto_20160727_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermoinfo',
            name='allowed_temp',
            field=models.BooleanField(default=True, verbose_name='Allowed Temperature ?'),
        ),
    ]
