# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=20, verbose_name='Situation')),
                ('recipient_list', models.TextField(blank=True, verbose_name='Recipient list')),
                ('thermo_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_log', to='catcher.ThermoInfo', verbose_name='Thermo Info')),
            ],
            options={
                'verbose_name': 'Mails Logs',
                'verbose_name_plural': 'Mail Log',
            },
        ),
    ]
