# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active ?'),
        ),
    ]
