# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_recipient_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillog',
            name='thermo_info',
        ),
        migrations.AddField(
            model_name='maillog',
            name='local',
            field=models.CharField(default='', max_length=150, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='temperature',
            field=models.FloatField(default=20, verbose_name='Temperature'),
        ),
    ]
