# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_auto_20160724_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
