# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_maillog_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maillog',
            options={'verbose_name': 'Mails Log', 'verbose_name_plural': 'Mail Logs'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name': 'Recipient', 'verbose_name_plural': 'Recipients'},
        ),
    ]
