# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('designed_by', models.CharField(max_length=50, verbose_name='Designed by')),
                ('version', models.CharField(max_length=10, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'System Information',
                'verbose_name_plural': 'System Information',
            },
        ),
    ]
