# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 29, 12, 50, 34, 762961, tzinfo=utc), verbose_name='Date'),
        ),
    ]
