# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systeminfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 7, 29, 12, 51, 7, 867438, tzinfo=utc), verbose_name='Date'),
        ),
    ]
